# @format

stages:
  - package

package-qa:
  image: docker:20.10.7
  stage: package
  only:
    - master
  variables:
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: '/certs'
  services:
    - name: docker:20.10.7-dind
      command: ['--insecure-registry=docker.oneshell.in']
  script:
    # Login to the Docker registry
    - echo $DOCKER_ONESHELL_PASSWORD | docker login --username $DOCKER_ONESHELL_USER --password-stdin docker.oneshell.in
    # Build the Docker image with the CI_COMMIT_SHA as the tag
    - docker build -t docker.oneshell.in/library/compose-builder:latest .
    - docker push docker.oneshell.in/library/compose-builder:latest
  after_script:
    # Clean up Docker images to save space
    - docker rmi docker.oneshell.in/library/compose-builder:latest
