# @format

stages:
  - package

package-qa:
  image: docker/compose:1.29.2
  stage: package
  only:
    - master
  services:
    - name: docker:20.10.7-dind
      command: ['--insecure-registry=docker.oneshell.in']
  before_script:
    - docker info
  script:
    - echo $DOCKER_ONESHELL_PASSWORD | docker login --username $DOCKER_ONESHELL_USER --password-stdin docker.oneshell.in
    - docker build -t docker.oneshell.in/library/compose-builder:latest .
    - docker push docker.oneshell.in/library/compose-builder:latest
