# @format

stages:
  - package

package:
  image: docker:20.10.7-compose
  stage: package
  services:
    - name: docker:20.10.7-dind
  script:
    - echo $DOCKER_ONESHELL_PASSWORD | docker login --username $DOCKER_ONESHELL_USER --password-stdin docker.oneshell.in
    - docker build -t docker.oneshell.in/library/compose-builder:latest .
    - docker push docker.oneshell.in/library/compose-builder:latest
