# @format

stages:
  - package

package-qa:
  image: docker:20.10.7
  stage: package
  only:
    - master
  variables:
    DOCKER_HOST: 'tcp://docker:2375' # Configure Docker-in-Docker daemon connection
    DOCKER_TLS_CERTDIR: '' # Disable TLS for Docker-in-Docker
    DOCKER_DRIVER: overlay2
  services:
    - name: docker:20.10.7-dind # Docker-in-Docker service
      alias: docker # Required alias to match the DOCKER_HOST
  script:
    # Login to the Docker registry
    - echo $DOCKER_ONESHELL_PASSWORD | docker login --username $DOCKER_ONESHELL_USER --password-stdin docker.oneshell.in
    # Build the Docker image
    - docker build -t docker.oneshell.in/library/compose-builder:latest .
    # Push the Docker image
    - docker push docker.oneshell.in/library/compose-builder:latest
